### ISSUE TITLE
Wrong redirect after Session expired

### ISSUE THREAD

**Issue by stiffler17** [adminfaces/admin-template#30] opened 2017-10-04 13:29 UTC
##### Issue Overview
Hi!

I have opened the following page.
https://localhost:8443/gebaeude/pages/gebaeude_list. xhtml
If the session dropped, I will be redirected to the login page. The last current page is saved to be redirected after login. Unfortunately, the URL is stored incorrectly if there is a subfolder
I will be redirected to the following URL.

URL at login.
https://localhost:8443/gebaeude/login.xhtml?page=%2Fpages_list. xhtml

URL after login.
https://localhost:8443/gebaeude/pages_list. xhtml

##### Expected Behaviour
Redirect to the correct page after a login.
https://localhost:8443/gebaeude/pages/gebaeude_list.xhtml

##### Additional Information
* Affected version: I am using com.github.adminfaces:admin-theme:1.0.0-RC9
* Browser version: N/A

![directory](https://user-images.githubusercontent.com/14252961/31178149-7d7714ec-a918-11e7-8bba-1f7474653fa0.PNG)

**Comment by rmpestano** [comment] 2017-10-04 20:42
Hi @stiffler17,

can you provide a sample maven project which reproduces the issue?

thank you very much!

**Comment by stiffler17** [comment] 2017-10-10 08:19
Hi!

Unfortunately, I can't help you with a Maven project.

But I can tell you how you can easily reproduce it.
You have an admin-starter-persistence repo.
Move the "car-list. xhtml" and the "car-form. xhtml" to a subfolder.
Then the error should occur when redirecting.

However, the error only occurs for subfolders that contain page names with a hyphen or underscore.

I hope I could help you with that.

**Comment by rmpestano** [comment] 2017-10-10 12:24
Hi, do you have a 'space' in the name of the file or it was a typo?  "car-list. xhtml" 

Anyway I could not reproduce the error here.

**Comment by rmpestano** [comment] 2017-10-10 12:29
Here is the maven project I've tested. It have the changes you proposed to reproduce the issue:
[admin-starter-persistence-subfolder.zip](https://github.com/adminfaces/admin-template/files/1371835/admin-starter-persistence-subfolder.zip)

**Comment by stiffler17** [comment] 2017-10-13 11:44
Hi!

Thank you for your sample project. It works fine.
But I have now found the error.

It depends on the URL.
If my subpage has the same name as my context name, the redirect does not work correctly.
https://localhost:8443/gebaeude/pages/gebaeude-list.xhtml
In my case, it's "gebaeude".

So. Rename your "admin-starter" to "car". After that, the redirect no longer works correctly.

**Comment by rmpestano** [comment] 2017-10-13 12:16
Hi @stiffler17,

now I got it, the AdminFilter removes contextPath when creating redirectUrl because of a corner case (redirect url is home page or just '/').

Now it should be fixed, can you try with the snapshot below?

```
<dependency>
         <groupId>com.github.adminfaces</groupId>
         <artifactId>admin-template</artifactId>
         <version>1.0.0-RC11-20171013.121240-2</version>
 </dependency>
```

You'll need to enable snapshots repository:

```
    <repositories>
        <repository>
            <snapshots/>
            <id>snapshots</id>
            <name>libs-snapshot</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```
Thank you very much for reporting it.

**Comment by rmpestano** [comment] 2017-10-13 22:36
The fix was included in RC11 release, any problem please reopen this issue.

**Closed by rmpestano** 2017-10-13 22:36 UTC
Labels: bug
