### ISSUE TITLE
The menus keep auto closing after a Ajax call in Glassfish 5

### ISSUE THREAD

**Issue by chrisfperes** [adminfaces/admin-template#31] opened 2017-10-05 17:46 UTC
`#####` Issue Overview

The expanded menus in the left side keep auto closing after using an ajax call from Primefaces.

##### Current Behaviour

Everytime I call an Ajax from PrimeFaces the Menus in the left side start to close everytime I try to open then. (The command p:ajax and p:poll are causing the problem.)

Version: RC9

**Comment by rmpestano** [comment] 2017-10-05 22:55
Hi,

do you have any sample project or code to share?

**Comment by chrisfperes** [comment] 2017-10-06 10:58
I discovered what the problem is. The Glassfish version 5.0 is causing the problem. I reverted to 4.1 and evertything is fine now. Do you recommend another server application?

**Comment by rmpestano** [comment] 2017-10-08 12:00
Hi @chrisfperes,

I've just reproduced here, on Glassfish 5 after an initial ajax call we can't open any sub menu.

Just could not figure out the cause so will left the issue opened.

**Comment by rmpestano** [comment] 2018-02-13 11:25
This issue was fixed in RC12 andwas related to PrimeFaces 6.2 upgrade.

PS: I still see other issues with Glassfish 5 like ajax loading bar does not closes after ajax completion in auto complete component, Calendar not shows up in dialog, etc...

 I will open separated issues for those cases.

**Closed by rmpestano** 2018-02-13 11:25 UTC
Labels: bug
